version: '3'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/opt/app/
      - /opt/app/node_modules
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
  
